Repository fzi-forschungszentrum-informatik/ros2_ros_bt_py, pull requests merged in 2025-05, with the labels that each got.

#177 Update Web-GUI to 4.0.1
  ros_bt_py_web_gui/html/assets/index-BppXkrA4.js
  ros_bt_py_web_gui/html/assets/index-DW-kJ25_.js
  ros_bt_py_web_gui/html/index.html
Labels: enhancement, GUI, bot

#170 Made documentation look more like the ROS documentation
  ros_bt_py/doc/source/advanced_tutorial.rst
  ros_bt_py/doc/source/basic_tutorial.rst
  ros_bt_py/doc/source/conf.py
  ros_bt_py/doc/source/configuration.rst
  ros_bt_py/doc/source/creating_a_node_class_package.rst
  ros_bt_py/doc/source/creating_node_classes.rst
  ros_bt_py/doc/source/getting_started.rst
  ros_bt_py/doc/source/index.rst
  ros_bt_py/doc/source/node_creation.rst
  ros_bt_py/doc/source/testing_node_classes.rst
  ros_bt_py/doc/source/tutorials.rst
Labels: documentation, enhancement, Core Library

#178 Fix launch file sets invalid parameter values.
  ros_bt_py/launch/ros_bt_py.launch.py
Labels: bug, Core Library
